cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

###### BREWS ######
brew 'ack'
brew 'awk'
brew 'awscli'
brew 'certbot'
brew 'clojure'
brew 'cmake'
brew 'coreutils'
brew 'cowsay'
brew 'curl'
brew 'docker-compose'
brew 'elasticsearch'
brew 'elixir'
brew 'emojify'
brew 'erlang'
brew 'fasd'
brew 'ffmpeg'
brew 'git'
brew 'go'
brew 'geoip'
brew 'grep'
brew 'hub'
brew 'htop'
brew 'httpd'
brew 'imagemagick'
brew 'jenkins'
brew 'jp2a'
brew 'jq'
brew 'jupyter'
brew 'kotlin'
brew 'kubernetes-cli'
brew 'libgit2'
brew 'llvm'
brew 'lua'
brew 'make'
brew 'mas'
brew 'memcached'
brew 'mongodb'
brew 'mysql'
brew 'nginx'
brew 'openssl'
brew 'nmap'
brew 'node'
brew 'nvm'
brew 'perl'
brew 'phantomjs'
brew 'pipenv'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'python'
brew 'r'§
brew 'rabbitmq'
brew 'readline'
brew 'redis'
brew 'rsync'
brew 'ruby'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'telnet'
brew 'tree'
brew 'tmux'
brew 'unrar'
brew 'vim'
brew 'watchman'
brew 'webp'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-syntax-highlighting'
# browse top packages at https://formulae.brew.sh/analytics/install-on-request/365d/

###### CASKS ######
cask '1password'
cask 'adobe-creative-cloud'
cask 'aerial'
cask 'alfred'
cask 'brave-browser'
cask 'charles'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'flux'
cask 'framer'
cask 'framer-x'
cask 'google-chrome'
cask 'google-drive'
cask 'grandperspective'
cask 'hammerspoon'
cask 'hyper'
cask 'iterm2'
cask 'karabiner-elements'
cask 'keycastr'
cask 'kindle'
cask 'moom'
cask 'mysqlworkbench'
cask 'notion'
cask 'now'
cask 'postman'
cask 'sip'
cask 'sirimote'
cask 'sketch'
cask 'skyfonts'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'

###### MAC APP STORE ######
mas 'Xcode', id: 497799835
mas 'SiteSucker', id: 442168834
mas 'Tweetbot', id: 557168941

# to search for available casks, use `brew search --casks` in the terminal.
# other applications not listed in the cask registry you may want:
# carbide create
# carbide motion
# lightroom classic
# lightroom cc
# photoshop cc
# after effects
# premiere pro
# fusion 360



