brew install deno
brew install git
brew install node
brew install pnpm
brew install ruby
brew install thefuck
brew install tmux
brew install vim
brew install yarn
brew install zsh
brew install zsh-syntax-highlighting
brew install ack
brew install awk
brew install awscli
brew install bat
brew install certbot
brew install cmake
brew install coreutils
brew install cowsay
brew install curl
brew install docker-compose
brew install deno
brew install elixir
brew install emojify
brew install erlang
brew install fasd
brew install ffmpeg
brew install fzf
brew install git
brew install go
brew install geoip
brew install grep
brew install hub
brew install htop
brew install httpd
brew install imagemagick
brew install jp2a
brew install jq
brew install jupyterlab
brew install kotlin
brew install kubernetes-cli
brew install libgit2
brew install llvm
brew install lua
brew install make
brew install mas
brew install memcached
brew install mobile-shell
brew install mongocli
brew install mysql
brew install nginx
brew install openssl
brew install nmap
brew install node
brew install nvm
brew install perl
brew install pipenv
brew install pnpm
brew install postgresql@14
brew install puma/puma/puma-dev
brew install python
brew install r
brew install rabbitmq
brew install readline
brew install redis
brew install ripgrep
brew install rsync
brew install ruby
brew install ruby-build
brew install rbenv
brew install roundup
brew install spaceman-diff
brew install spark
brew install telnet
brew install thefuck
brew install tree
brew install tmux
brew install vim
brew install watchman
brew install webp
brew install wget
brew install yarn
brew install zsh
brew install zsh-syntax-highlighting
# browse top packages at https://formulae.brew install.sh/analytics/install-on-request/365d/
