cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

###### FORMULA ######
brew 'ack'
brew 'awk'
brew 'awscli'
brew 'certbot'
brew 'clojure'
brew 'cmake'
brew 'coreutils'
brew 'cowsay'
brew 'curl'
brew 'docker-compose'
brew 'elixir'
brew 'emojify'
brew 'erlang'
brew 'fasd'
brew 'ffmpeg'
brew 'fzf'
brew 'git'
brew 'go'
brew 'geoip'
brew 'grep'
brew 'hub'
brew 'htop'
brew 'httpd'
brew 'imagemagick'
brew 'java'
brew 'jenkins'
brew 'jp2a'
brew 'jq'
brew 'jupyterlab'
brew 'kotlin'
brew 'kubernetes-cli'
brew 'libgit2'
brew 'llvm'
brew 'lua'
brew 'make'
brew 'mas'
brew 'memcached'
brew 'mobile-shell'
brew 'mongocli'
brew 'mysql'
brew 'nginx'
brew 'openssl'
brew 'nmap'
brew 'node'
brew 'nvm'
brew 'perl'
brew 'pipenv'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'python'
brew 'r'
brew 'rabbitmq'
brew 'readline'
brew 'redis'
brew 'ripgrep'
brew 'rsync'
brew 'ruby'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'telnet'
brew 'tree'
brew 'tmux'
brew 'vim'
brew 'watchman'
brew 'webp'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-syntax-highlighting'
# browse top packages at https://formulae.brew.sh/analytics/install-on-request/365d/

###### CASKS ######
cask '1password'
cask 'alfred'
cask 'around'
cask 'brave-browser'
cask 'charles'
cask 'contexts'
cask 'firefox'
cask 'freedom'
cask 'google-chrome'
cask 'grandperspective'
cask 'insomnia'
cask 'iterm2'
cask 'karabiner-elements'
cask 'loom'
cask 'notion'
cask 'pictogram'
cask 'pop'
cask 'postman'
cask 'sip'
cask 'sitesucker-pro'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'tidal'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoom'







##### Applications to install manually #####
# XCode
# Global Protect
# Adobe Creative Cloud + Lightroom, Photoshop, Illustrator
# Sketchup Pro


##### iOS Apps to maybe add
# Youtube
# Audible
# Overcast
# AllTrails
# Disney+
# HBOMax
# Google Maps
# Signal
# Mountain Project
# Google Sheets
# Venmo
# Robinhood
# Strava
# Coinbase
# Kindle
# Airbnb
